[env]
EDITOR = "nvim"

[tools]
# these tools are outside the sorted block because
# they are required for language specific backends
uv = "latest"
node = "latest"
go = "latest"
rust = "latest"
# keep-sorted start
"cargo:starship-jj" = "latest"
"go:github.com/google/keep-sorted" = "latest"
"npm:aws-cdk" = "latest"
"npm:hunkdiff" = "latest"
"npm:oxfmt" = "latest"
"npm:oxlint" = "latest"
"npm:tdd-guard" = "latest"
"npm:typescript-language-server" = "latest"
"pipx:claude-conversation-extractor" = "latest"
act = "latest"
age = "latest"
ast-grep = "latest"
atuin = "latest"
aws-cli = { version = "2.36.5", symlink_bins = "true" }
bat = "latest"
bat-extras = "latest"
biome = "latest"
bun = "latest"
carapace = "latest"
chezmoi = "latest"
claude = "latest"
codex = "latest"
delta = "latest"
difftastic = "latest"
eza = "latest"
fd = "latest"
fnox = "latest"
fzf = "latest"
gh = "latest"
ghcup = "latest"
gitui = "latest"
glow = "latest"
grex = "latest"
gum = "latest"
hexyl = "latest"
hyperfine = "latest"
java = "21"
jj = "latest"
jjui = "latest"
just = "latest"
ktlint = "latest"
lazydocker = "latest"
lazygit = "latest"
lefthook = "latest"
mani = "latest"
maven = "latest"
mprocs = "latest"
neovim = "latest"
pandoc = "latest"
pnpm = "10.33.0"
pre-commit = "latest"
prettier = "latest"
rclone = "latest"
ripgrep = "latest"
ruff = "latest"
sd = "latest"
sentry = "latest"
shellcheck = "latest"
sops = "latest"
starship = "latest"
supabase = "latest"
taplo = "latest"
television = "latest"
terraform = "latest"
vercel = "53"
watchexec = "latest"
yamlfmt = "latest"
yazi = "latest"
yt-dlp = "latest"
zellij = "latest"
zoxide = "latest"
# keep-sorted end

[settings]
experimental = true
