name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run chezmoi
        run: sudo sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply bibhubhatta
        
